#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "nord"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    enable_os_fileformat_icon = true
    enable_filetree_gitstatus = true
    github_username = 'Song921012'
    statusline_unicode_symbols = true
    relativenumber = false
    automatic_update = true
    lint_engine = "ale"
    #filetree_direction = "left"
[[layers]]
    name = 'core'
    enable_filetree_gitstatus = true
    enable_filetree_filetypeicon = true
    
[[layers]]
    name = 'core#statusline'
    enable = true
[[layers]]
    name = 'core#tabline'
    enable = true
    
[[layers]]
    name = 'incsearch'
    enable = true
[[layers]]
    name = 'foldsearch'
    enable = true

[[layers]]
  name = "colorscheme"
[[layers]]
  name = "git"
  git_plugin = 'fugitive'
#[[layers]]
#  name = 'telescope'
#  enable = 'has("nvim")'
[[layers]]
  name = 'leaderf'
#  enable = '!has("nvim")'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "lsp"


[[layers]]
  name = "lang#python"
  python_file_head = [
      '# -*- coding: utf-8 -*-',
      '# Author: Pengfei',
      '# Mail: aidishage@gmail.com'
      '# Created Time: `strftime("%a %b %d")`'
      ''
  ]

[[layers]]
  name = "lang#c"
  
[[layers]]
  name = "lang#cmake"

  
[[layers]]
  name = "lang#r"
  repl_command = "R --save"


[[layers]]
  name = "lang#julia"

[[layers]]
  name = "lang#ipynb"

[[layers]]
  name = "lang#markdown"
  enableWcwidth = 1
  listItemIndent = 1
  enabled_formater = ['prettier']

[[layers]]
  name = "lang#toml"
  
[[layers]]
  name = "ui"
  enable_scrollbar = true



[[layers]]
  name = "lang#latex"

[[layers]]
  name = "lang#sh"


[[layers]]
  name = "format"

[[layers]]
   name = "debug"

[[layers]]
  name = "checkers"
  lint_on_the_fly  = true
  lint_on_save = true

[[layers]]
   name = "chinese"
   enable = true

[[layers]]
  name = "treesitter"
  
  
[[layers]]
name = 'tools'
  
[[layers]]
  name = "tmux"
  
[[custom_plugins]]
  repo = "christoomey/vim-tmux-navigator"
  merged = false
[[custom_plugins]]
  repo = "luochen1990/rainbow"
  merged = false
  
[[custom_plugins]]
  repo = "lukas-reineke/indent-blankline.nvim"
  merged = false
  
#[[custom_plugins]]
#  repo = "nvim-lua/plenary.nvim"
#  merged = false
   

