format = """
$username\
$sudo\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D)\
"""
add_newline = true
right_format = """
$package\
$conda\
$c\
$cmake\
[](fg:#86BBD8 bg:#75a1ff)\
$julia\
[](fg:#75a1ff bg:#60baec)\
$python\
[](fg:#60baec bg:#86BBD8)\
$rlang\
$nodejs\
$env_var\
$docker_context\
[](fg:#86BBD8 bg:#33658A)\
$cmd_duration\
$time\
$memory_usage\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[sudo]
disabled = false
style = "bg:#9A348E"
format = '[ $symbol]($style)'

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[cmake]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[conda]
style = "bg:#86BBD8"
format = '[ $symbol$environment]($style)'
ignore_base = false


[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[julia]
symbol = " "
style = "bg:#75a1ff"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#60baec"
format = '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) ) ]($style)'

[rlang]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol $context ]($style) $path'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
[memory_usage]
disabled = false
threshold = 70
style = "bg:#33658A"
format = "[${ram}]($style)"
[cmd_duration]
disabled = false
style = "bg:#33658A"
format = "[$duration]($style)"
